%% Declaração fato Preferencia_rofessor

%% Preferencias Professor_1
professor_preferencia(professor_, inovação_e_Criatividade, 5).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 5).
professor_preferencia(professor_, resolução_de_Problemas_III, 5).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 2).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 2).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 2).
professor_preferencia(professor_, matemática_Discreta_--_ES, 1).


%% Preferencias Professor_2
professor_preferencia(professor_, inovação_e_Criatividade, 4).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 3).
professor_preferencia(professor_, resolução_de_Problemas_III, 5).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 1).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 2).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 2).
professor_preferencia(professor_, matemática_Discreta_--_ES, 2).

%% Preferencias Professor_3
professor_preferencia(professor_, inovação_e_Criatividade, 5).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 5).
professor_preferencia(professor_, resolução_de_Problemas_III, 5).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 3).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 5).
professor_preferencia(professor_, linguagens_Formais_--_ES, 1).
professor_preferencia(professor_, lógica_Matemática_--_ES, 1).
professor_preferencia(professor_, matemática_Discreta_--_ES, 1).

%% Preferencias Professor_4
professor_preferencia(professor_, inovação_e_Criatividade, 5).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 5).
professor_preferencia(professor_, resolução_de_Problemas_III, 3).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 1).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 1).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 4).
professor_preferencia(professor_, matemática_Discreta_--_ES, 3).

%% Preferencias Professor_5
professor_preferencia(professor_, inovação_e_Criatividade, 4).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 3).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 2).
professor_preferencia(professor_, resolução_de_Problemas_III, 4).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 3).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 4).
professor_preferencia(professor_, matemática_Discreta_--_ES, 4).

%% Preferencias Professor_6
professor_preferencia(professor_, inovação_e_Criatividade, 4).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 3).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 1).
professor_preferencia(professor_, resolução_de_Problemas_III, 5).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 3).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 3).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_7
professor_preferencia(professor_, inovação_e_Criatividade, 5).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 3).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 5).
professor_preferencia(professor_, resolução_de_Problemas_III, 5).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 1).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 2).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_8
professor_preferencia(professor_, inovação_e_Criatividade, 5).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 5).
professor_preferencia(professor_, resolução_de_Problemas_III, 5).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 1).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 1).
professor_preferencia(professor_, linguagens_Formais_--_ES, 4).
professor_preferencia(professor_, lógica_Matemática_--_ES, 1).
professor_preferencia(professor_, matemática_Discreta_--_ES, 4).

%% Preferencias Professor_9
professor_preferencia(professor_, inovação_e_Criatividade, 1).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 3).
professor_preferencia(professor_, resolução_de_Problemas_III, 5).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, ).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 5).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_10
professor_preferencia(professor_, inovação_e_Criatividade, 3).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 4).
professor_preferencia(professor_, resolução_de_Problemas_III, 4).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 3).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 3).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_11
professor_preferencia(professor_, inovação_e_Criatividade, 5).
professor_preferencia(professor_, análise_e_Projeto_de_Software, 3).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 1).
professor_preferencia(professor_, resolução_de_Problemas_III, 5).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, 5).
professor_preferencia(professor_, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_, estruturas_de_Dados_--_ES, 5).
professor_preferencia(professor_, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_12
professor_preferencia(professor_12, inovação_e_Criatividade, 3).
professor_preferencia(professor_12, análise_e_Projeto_de_Software, 1).
professor_preferencia(professor_12, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 2).
professor_preferencia(professor_12, resolução_de_Problemas_III, 3).
professor_preferencia(professor_12, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_12, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_12, estruturas_de_Dados_--_ES, 2).
professor_preferencia(professor_12, linguagens_Formais_--_ES, 4).
professor_preferencia(professor_12, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_12, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_13
professor_preferencia(professor_13, inovação_e_Criatividade, 5).
professor_preferencia(professor_13, análise_e_Projeto_de_Software, 1).
professor_preferencia(professor_13, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 1).
professor_preferencia(professor_13, resolução_de_Problemas_III, 4).
professor_preferencia(professor_13, algoritmos_e_Programação_--_ES, 2).
professor_preferencia(professor_13, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_13, estruturas_de_Dados_--_ES, 3).
professor_preferencia(professor_13, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_13, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_13, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_14
professor_preferencia(professor_14, inovação_e_Criatividade, 5).
professor_preferencia(professor_14, análise_e_Projeto_de_Software, 2).
professor_preferencia(professor_14, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 2).
professor_preferencia(professor_14, resolução_de_Problemas_III, 4).
professor_preferencia(professor_14, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_14, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_14, estruturas_de_Dados_--_ES, 1).
professor_preferencia(professor_14, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_14, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_14, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_15
professor_preferencia(professor_15, inovação_e_Criatividade, 5).
professor_preferencia(professor_15, análise_e_Projeto_de_Software, 1).
professor_preferencia(professor_15, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 1).
professor_preferencia(professor_15, resolução_de_Problemas_III, 1).
professor_preferencia(professor_15, algoritmos_e_Programação_--_ES, 3).
professor_preferencia(professor_15, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_15, estruturas_de_Dados_--_ES, 3).
professor_preferencia(professor_15, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_15, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_15, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_16
professor_preferencia(professor_16, inovação_e_Criatividade, 5).
professor_preferencia(professor_16, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_16, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 5).
professor_preferencia(professor_16, resolução_de_Problemas_III, 5).
professor_preferencia(professor_16, algoritmos_e_Programação_--_ES, 5).
professor_preferencia(professor_16, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_16, estruturas_de_Dados_--_ES, 5).
professor_preferencia(professor_16, linguagens_Formais_--_ES, 1).
professor_preferencia(professor_16, lógica_Matemática_--_ES, 1).
professor_preferencia(professor_16, matemática_Discreta_--_ES, 1).

%% Preferencias Professor_17
professor_preferencia(professor_17, inovação_e_Criatividade, 5).
professor_preferencia(professor_17, análise_e_Projeto_de_Software, 2).
professor_preferencia(professor_17, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 1).
professor_preferencia(professor_17, resolução_de_Problemas_III, 3).
professor_preferencia(professor_17, algoritmos_e_Programação_--_ES, 5).
professor_preferencia(professor_17, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_17, estruturas_de_Dados_--_ES, 5).
professor_preferencia(professor_17, linguagens_Formais_--_ES, 4).
professor_preferencia(professor_17, lógica_Matemática_--_ES, 4).
professor_preferencia(professor_17, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_18
professor_preferencia(professor_, inovação_e_Criatividade, ).
professor_preferencia(professor_, análise_e_Projeto_de_Software, ).
professor_preferencia(professor_, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), ).
professor_preferencia(professor_, resolução_de_Problemas_III, ).
professor_preferencia(professor_, algoritmos_e_Programação_--_ES, ).
professor_preferencia(professor_18, arquitetura_e_Organização_de_Computadores_--_ES, ).
professor_preferencia(professor_18, estruturas_de_Dados_--_ES, ).
professor_preferencia(professor_18, linguagens_Formais_--_ES, ).
professor_preferencia(professor_18, lógica_Matemática_--_ES, ).
professor_preferencia(professor_18, matemática_Discreta_--_ES, ).

%% Preferencias Professor_19
professor_preferencia(professor_18, inovação_e_Criatividade, 5).
professor_preferencia(professor_18, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_18, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 5).
professor_preferencia(professor_18, resolução_de_Problemas_III, 5).
professor_preferencia(professor_18, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_18, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_18, estruturas_de_Dados_--_ES, 1).
professor_preferencia(professor_18, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_18, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_18, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_20
professor_preferencia(professor_20, inovação_e_Criatividade, 5).
professor_preferencia(professor_20, análise_e_Projeto_de_Software, 5).
professor_preferencia(professor_20, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 5).
professor_preferencia(professor_20, resolução_de_Problemas_III, 5).
professor_preferencia(professor_20, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_20, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_20, estruturas_de_Dados_--_ES, 1).
professor_preferencia(professor_20, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_20, lógica_Matemática_--_ES, 3).
professor_preferencia(professor_20, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_21
professor_preferencia(professor_21, inovação_e_Criatividade, 5).
professor_preferencia(professor_21, análise_e_Projeto_de_Software, 4).
professor_preferencia(professor_21, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 4).
professor_preferencia(professor_21, resolução_de_Problemas_III, 4).
professor_preferencia(professor_21, algoritmos_e_Programação_--_ES, 1).
professor_preferencia(professor_21, arquitetura_e_Organização_de_Computadores_--_ES, 3).
professor_preferencia(professor_21, estruturas_de_Dados_--_ES, 2).
professor_preferencia(professor_21, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_21, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_21, matemática_Discreta_--_ES, 5).

%% Preferencias Professor_22
professor_preferencia(professor_22, inovação_e_Criatividade, 2).
professor_preferencia(professor_22, análise_e_Projeto_de_Software, 2).
professor_preferencia(professor_22, resolução_de_Problemas_I_(Eng._Requisitos_-_Extensão), 1).
professor_preferencia(professor_22, resolução_de_Problemas_III, 5).
professor_preferencia(professor_22, algoritmos_e_Programação_--_ES, 4).
professor_preferencia(professor_22, arquitetura_e_Organização_de_Computadores_--_ES, 5).
professor_preferencia(professor_22, estruturas_de_Dados_--_ES, 4).
professor_preferencia(professor_22, linguagens_Formais_--_ES, 5).
professor_preferencia(professor_22, lógica_Matemática_--_ES, 5).
professor_preferencia(professor_22, matemática_Discreta_--_ES, 5).
